version: '2'

networks:
  default:
    external:
      name: bridge

services:
  sitespeedmanager.agent:
    network_mode: bridge
    image: sitespeedmanager.agent
    build:
      context: ./SiteSpeedManager.Agent
      dockerfile: Dockerfile
